Repository coollabsio/coolify, pull requests merged in 2024-08, with the labels that each got.

#3068 fix: docker compose destination network
  app/Livewire/Project/New/DockerCompose.php
  app/Models/Service.php
Labels: 💤 Waiting for feedback

#3190 Fix: WordPress and ClassicPress with MySQL have no ARM images
  templates/compose/classicpress-with-mysql.yaml
  templates/compose/wordpress-with-mysql.yaml
Labels: 🔴 Live-stream

#3118 Fix: Preselect environment when coming form the project screen
  resources/views/livewire/dashboard.blade.php
  resources/views/livewire/project/index.blade.php
Labels: 🔴 Live-stream

#2989 fix: Added default message queue type to twenty template
  templates/compose/twenty.yaml
Labels: 🔴 Live-stream

#3015 Improvement: New CONTRIBUTING.md and some cleanup of the installation files
  .env.development.example
  .env.production
  CONTRIBUTING.md
  CONTRIBUTION.md
  docker-compose.prod.yml
  docker-compose.windows.yml
  docker-compose.yml
  scripts/install.sh
Labels: 🚀 Improvement, 👨‍🏭 Next, 🔴 Live-stream
