Repository coollabsio/coolify, pull requests merged in 2024-10, with the labels that each got.

#3613 refactor: Update search input placeholder in resource index view
  resources/views/livewire/project/resource/index.blade.php
Labels: 💤 Waiting for feedback

#2980 New services: LLM & AI-related one-click services
  public/svgs/anythingllm.svg
  public/svgs/argilla.png
  public/svgs/infisical.png
  public/svgs/langfuse.png
  public/svgs/litellm.svg
  public/svgs/prefect.png
  public/svgs/qdrant.png
  public/svgs/searxng.svg
  public/svgs/unstructured.png
  public/svgs/weaviate.png
  templates/compose/anythingllm.yaml
  templates/compose/argilla.yaml
  templates/compose/infisical.yaml
  templates/compose/langfuse.yaml
  templates/compose/litellm.yaml
  templates/compose/prefect.yaml
  templates/compose/qdrant.yaml
  templates/compose/searxng.yaml
  templates/compose/unstructured.yaml
  templates/compose/weaviate.yaml
Labels: ⚙️ New Service

#3748 Fix: Broken helper manifests (for a short period a few hours)
  other/nightly/versions.json
  versions.json
Labels: 🔴 High Priority, 🏔️ Peaklabs

#3127 Feat: getoutline service
  public/svgs/getoutline.jpeg
  templates/compose/getoutline.yaml
Labels: ⚙️ New Service

#3570 chore: add Nitropage service template and logo
  public/svgs/nitropage.svg
  templates/compose/nitropage-with-postgresql.yaml
  templates/compose/nitropage.yaml
Labels: ⚙️ New Service

#2383 feat: Add Supertokens template
  public/svgs/supertokens.svg
  templates/compose/supertokens.yaml
Labels: ⚙️ New Service

#3330 fix rabbit-mq
  templates/compose/rabbitmq.yaml
Labels: 💤 Waiting for feedback, ⚙️ New Service

#2885 feat: add easyappointments service template
  public/svgs/easyappointments.png
  templates/compose/easyappointments.yaml
Labels: ⚙️ New Service

#3198 feat: Update Authentik
  templates/compose/authentik.yaml
Labels: ⚙️ New Service

#3249 added libreoffice
  public/svgs/libreoffice.svg
  templates/compose/libreoffice.yaml
Labels: ⚙️ New Service

#3008 feat: Add organizr
  public/svgs/organizr.png
  templates/compose/organizr.yaml
Labels: ⚙️ New Service

#3763 Feat: Service fixes and new services
  public/svgs/dozzle.svg
  public/svgs/easyappointments.png
  public/svgs/libreoffice.svg
  public/svgs/organizr.png
  public/svgs/soketi.jpeg
  public/svgs/soketi.png
  public/svgs/supertokens.svg
  templates/compose/authentik.yaml
  templates/compose/dozzle-with-auth.yaml
  templates/compose/dozzle.yaml
  templates/compose/easyappointments.yaml
  templates/compose/libreoffice.yaml
  templates/compose/organizr.yaml
  templates/compose/rabbitmq.yaml
  templates/compose/soketi.yaml
  templates/compose/supertokens-with-mysql.yaml
  templates/compose/supertokens-with-postgresql.yaml
  templates/compose/windmill.yaml
  templates/service-templates.json
Labels: 🏔️ Peaklabs

#2695 Add service template for azimutt
  public/svgs/azimutt.svg
  templates/compose/azimutt.yaml
Labels: ⚙️ New Service

#2719 Adding service for paperless
  public/svgs/paperless.svg
  templates/compose/paperless.yaml
Labels: ⚙️ New Service

#2722 [TEMPLATE] Forgejo template (with single runner)
  public/svgs/forgejo.svg
  templates/compose/forgejo-with-mariadb.yaml
  templates/compose/forgejo-with-mysql.yaml
  templates/compose/forgejo-with-postgresql.yaml
  templates/compose/forgejo-with-runner-with-mariadb.yaml
  templates/compose/forgejo-with-runner-with-mysql.yaml
  templates/compose/forgejo-with-runner-with-postgresql.yaml
  templates/compose/forgejo-with-runner.yaml
  templates/compose/forgejo.yaml
Labels: ⚙️ New Service

#2934 added bookstack template
  templates/compose/bookstack.yaml
Labels: ⚙️ New Service

#2978 feat: Add Mautic 4 and 5 to service templates
  public/svgs/mautic.svg
  templates/compose/mautic4.yaml
  templates/compose/mautic5.yaml
Labels: ⚙️ New Service

#3103 fix: update mattermost image tag and add default port
  public/svgs/mattermost.svg
  templates/compose/mattermost.yaml
Labels: ⚙️ New Service

#3109 feat: add keycloak template
  public/svgs/keycloak.svg
  templates/compose/keycloak-with-postgres.yaml
  templates/compose/keycloak.yaml
Labels: ⚙️ New Service

#3033 feat: add joplin server
  public/svgs/joplin.png
  templates/compose/joplin.yaml
Labels: ⚙️ New Service

#3111 feat: add onedev template
  public/svgs/onedev.svg
  templates/compose/onedev.yaml
Labels: ⚙️ New Service

#3214 feat: Add freshrss service template
  templates/compose/freshrss.yaml
Labels: ⚙️ New Service

#3213 feat: Add Traccar template
  templates/compose/traccar.yml
Labels: ⚙️ New Service

#3219 Add Vvveb CMS template
  public/svgs/vvveb.svg
  templates/compose/vvveb-with-mariadb.yml
  templates/compose/vvveb-without-database.yml
  templates/compose/vvveb.yml
Labels: ⚙️ New Service

#3199 feat: add Nextcloud with Postgres template
  templates/compose/nextcloud-with-postgres.yaml
Labels: ⚙️ New Service

#3435 Add kimai template
  public/svgs/kimai.svg
  templates/compose/kimai.yaml
Labels: ⚙️ New Service

#3123 feat: Added Unsend template
  public/svgs/unsend.svg
  templates/compose/resend.yaml
Labels: ⚙️ New Service

#3117 feat: add ntfy template
  public/svgs/ntfy.svg
  templates/compose/ntfy.yaml
Labels: ⚙️ New Service

#3715 Add qBittorrent template
  public/svgs/qbittorrent.svg
  templates/compose/qbittorrent.yaml
Labels: ⚙️ New Service

#3695 feat: add Homebox template
  public/svgs/homebox.svg
  templates/compose/homebox.yaml
Labels: ⚙️ New Service

#3328 add cryptgeon template
  templates/compose/cryptgeon.yaml
Labels: ⚙️ New Service

#3724 feat: add owncloud service and logo
  public/svgs/owncloud.svg
  templates/compose/owncloud.yaml
Labels: ⚙️ Service

#3446 feat: add immich service
  public/svgs/immich.svg
  templates/compose/immich.yaml
Labels: ⚙️ Service

#3727 Service: Flowise
  public/svgs/flowise.png
  templates/compose/flowise-with-databases.yaml
  templates/compose/flowise.yaml
Labels: ⚙️ Service

#3738 feat: affine service template and logo
  public/svgs/affine.svg
  templates/compose/affine.yaml
Labels: ⚙️ Service

#3785 Feat: New services and service fixes part 2
  public/svgs/audiobookshelf.svg
  public/svgs/azimutt.png
  public/svgs/bookstack.png
  public/svgs/forgejo.svg
  public/svgs/joplin.png
  public/svgs/keycloak.svg
  public/svgs/mattermost.svg
  public/svgs/mautic.svg
  public/svgs/onedev.svg
  public/svgs/paperless.svg
  templates/compose/audiobookshelf.yaml
  templates/compose/azimutt.yaml
  templates/compose/bookstack.yaml
  templates/compose/forgejo-with-mariadb.yaml
  templates/compose/forgejo-with-mysql.yaml
  templates/compose/forgejo-with-postgresql.yaml
  templates/compose/forgejo-with-runner-with-mariadb.yaml
  templates/compose/forgejo-with-runner-with-mysql.yaml
  templates/compose/forgejo-with-runner-with-postgresql.yaml
  templates/compose/forgejo-with-runner.yaml
  templates/compose/forgejo.yaml
  templates/compose/getoutline.yaml
  templates/compose/joplin.yaml
  templates/compose/keycloak-with-postgres.yaml
  templates/compose/keycloak.yaml
  templates/compose/mattermost.yaml
  templates/compose/mautic4.yaml
  templates/compose/mautic5.yaml
  templates/compose/onedev.yaml
  templates/compose/paperless.yaml
  templates/compose/posthog.yaml
  templates/service-templates.json
Labels: 🏔️ Peaklabs

#3823 Add LibreTranslate template
  public/svgs/libretranslate.svg
  templates/compose/libretranslate.yaml
Labels: ⚙️ Service

#3515 Add template for HeyForm
  public/svgs/heyform.svg
  templates/compose/heyform.yaml
Labels: ⚙️ Service

#3110 feat: add zipline template
  templates/compose/zipline.yaml
Labels: ⚙️ Service

#3074 feat: Added Dify template
  public/svgs/dify.png
  templates/compose/dify.yaml
Labels: ⚙️ Service

#3788 Fix plane template
  templates/compose/plane.yaml
Labels: ⚙️ Service

#3810 Update supabase add supavisor
  templates/compose/supabase.yaml
Labels: ⚙️ Service

#3867 Service: osticket
  public/svgs/osticket.png
  templates/compose/osticket.yaml
Labels: 💤 Waiting for feedback, ⚙️ Service

#3251 feat: add Calcom template
  public/svgs/calcom.svg
  templates/compose/calcom.yaml
Labels: ⚙️ Service

#2058 feat: add edgedb configuration
  public/svgs/edgedb.svg
  templates/compose/edgedb.yaml
Labels: 💤 Waiting for feedback, ⚙️ Database

#3855 Service Mosquitto
  public/svgs/mosquitto.png
  templates/compose/mosquitto.yaml
Labels: ⚙️ Service

#3184 Fix: Redis DB UI
  app/Actions/Database/StartRedis.php
  app/Livewire/Project/Database/Redis/General.php
  app/Models/EnvironmentVariable.php
  app/Models/StandaloneRedis.php
  bootstrap/helpers/databases.php
  database/migrations/2024_08_21_165435_add_redis_username_to_standalone_redis_table.php
  database/migrations/2024_10_15_172139_add_is_shared_to_environment_variables.php
  database/migrations/2024_10_16_120026_encrypt_existing_redis_passwords.php
  resources/views/livewire/project/database/redis/general.blade.php
Labels: 🏔️ Peaklabs

#3934 Feat: Ability to disable tow step confirmation
  app/Livewire/Settings/Index.php
  database/migrations/2024_10_16_192133_add_confirmation_settings_to_instance_settings_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/DisableTwoStepConfirmationSeeder.php
  resources/views/components/modal-confirmation.blade.php
  resources/views/livewire/server/delete.blade.php
  resources/views/livewire/settings/index.blade.php
Labels: 🏔️ Peaklabs

#3913 Fix: 2 minor proxy issues
  app/Actions/Docker/GetContainersStatus.php
  app/Jobs/ServerCheckJob.php
  bootstrap/helpers/proxy.php
Labels: 🏔️ Peaklabs

#3907 Embedded messages for Discord notifications
  app/Jobs/SendMessageToDiscordJob.php
  app/Notifications/Application/DeploymentFailed.php
  app/Notifications/Application/DeploymentSuccess.php
  app/Notifications/Application/StatusChanged.php
  app/Notifications/Channels/DiscordChannel.php
  app/Notifications/Container/ContainerRestarted.php
  app/Notifications/Container/ContainerStopped.php
  app/Notifications/Database/BackupFailed.php
  app/Notifications/Database/BackupSuccess.php
  app/Notifications/Database/DailyBackup.php
  app/Notifications/Dto/DiscordMessage.php
  app/Notifications/Internal/GeneralNotification.php
  app/Notifications/ScheduledTask/TaskFailed.php
  app/Notifications/Server/DockerCleanup.php
  app/Notifications/Server/ForceDisabled.php
  app/Notifications/Server/ForceEnabled.php
  app/Notifications/Server/HighDiskUsage.php
  app/Notifications/Server/Revived.php
  app/Notifications/Server/Unreachable.php
  app/Notifications/Test.php
Labels: 🛠️ Feature

#3947 Fix: Required environment variable throws and errors when updating shared variables
  app/Livewire/Project/Shared/EnvironmentVariable/Show.php
Labels: 🏔️ Peaklabs

#3955 feat: add wireguard-easy template
  public/svgs/wireguard.svg
  templates/compose/wireguard-easy.yaml
Labels: ⚙️ Service

#3717 Fix: Trigger.dev
  templates/compose/trigger-with-external-database.yaml
  templates/compose/trigger.yaml
Labels: ⚙️ Service

#3974 Fix: Disable tow step confirmation when there is a password throws and error
  app/Livewire/NavbarDeleteTeam.php
  app/Livewire/Project/Database/BackupEdit.php
  app/Livewire/Project/Database/BackupExecutions.php
  app/Livewire/Project/Service/FileStorage.php
  app/Livewire/Project/Service/ServiceApplicationView.php
  app/Livewire/Project/Shared/Danger.php
  app/Livewire/Project/Shared/Destination.php
  app/Livewire/Project/Shared/Storages/Show.php
  app/Livewire/Server/Delete.php
  app/Livewire/Team/AdminView.php
Labels: 🏔️ Peaklabs

#3956 Jupyterlab Notebook Template
  public/svgs/jupyterlab.svg
  templates/compose/jupyterlab.yaml
Labels: 💤 Waiting for feedback, ⚙️ Service

#3927 Fix and improve OTP UI
  resources/views/livewire/profile/index.blade.php
Labels: 🏔️ Peaklabs

#3995 Update reactive-resume.yaml to enable one click deployment
  templates/compose/reactive-resume.yaml
Labels: ⚙️ Service

#3979 feat: Foundry Virtual Tabletop template
  public/svgs/foundryvtt.png
  templates/compose/foundryvtt.yaml
Labels: 💤 Waiting for feedback, ⚙️ Service

#4007 Fix 2 step deletion
  app/Livewire/NavbarDeleteTeam.php
  app/Livewire/Project/Database/BackupEdit.php
  app/Livewire/Project/Database/BackupExecutions.php
  app/Livewire/Project/Service/FileStorage.php
  app/Livewire/Project/Service/ServiceApplicationView.php
  app/Livewire/Project/Shared/Danger.php
  app/Livewire/Project/Shared/Destination.php
  app/Livewire/Project/Shared/Storages/Show.php
  app/Livewire/Server/Delete.php
  app/Livewire/Settings/Index.php
  app/Livewire/Team/AdminView.php
Labels: 🏔️ Peaklabs

#4014 Fix: Mosquitto service
  templates/compose/mosquitto.yaml
Labels: 💤 Waiting for feedback, ⚙️ Service

#4023 Upgrade Keycloak Template to v26.0
  templates/compose/keycloak-with-postgres.yaml
  templates/compose/keycloak.yaml
Labels: ⚙️ Service

#3704 feat: add coder service
  public/svgs/coder.svg
  templates/compose/coder.yaml
Labels: ⚙️ Service

#4026 Adjusted bitcoin core service, especially how to run the rpc in a sec…
  templates/compose/bitcoin-core.yaml
Labels: ⚙️ Service

#4017 Fix: 2-step confirmation button rendering bug
  resources/views/components/modal-confirmation.blade.php
Labels: 🏔️ Peaklabs

#4046 fix volume mediawiki.yaml
  templates/compose/mediawiki.yaml
Labels: ⚙️ Service

#4068 Design: More Space and Visual Hierarchy
  resources/css/app.css
  resources/views/components/navbar.blade.php
  resources/views/layouts/app.blade.php
  resources/views/livewire/dashboard.blade.php
Labels: 💤 Waiting for feedback

#3824 Some composer.json files change
  composer.json
  composer.lock
Labels: 💤 Waiting for feedback
