Repository coollabsio/coolify, pull requests merged in 2024-09, with the labels that each got.

#3201 feat: add Plunk template
  public/svgs/plunk.svg
  templates/compose/plunk.yaml
Labels: ⚙️ New Service

#3353 Fix: Pull helper image if not available otherwise s3 backup upload fails
  app/Jobs/DatabaseBackupJob.php
Labels: 🐞 Bug, 👨‍🏭 Next, 🦟 Confirmed Bug, Medium Priority

#3539 Fix: Ray error on development
  .env.development.example
  config/clockwork.php
  other/nightly/.env.development.example
Labels: 🚧 Next

#3522 Add hint to "build variable" check in the enviroment variable tab. Remember the user what should be doing in order to make it work.
  resources/views/livewire/project/shared/environment-variable/add.blade.php
  resources/views/livewire/project/shared/environment-variable/show.blade.php
Labels: 🚧 Next

#3481 Feat: New pull request template
  .github/pull_request_template.md
Labels: 🚧 Next

#3480 FIXES: #3322 deploy DB alterations before starting the service
  templates/compose/logto.yaml
Labels: 🚧 Next

#3490 Feat: Improve release.md
  RELEASE.md
Labels: 🏔️ Peaklabs

#3518 Refactor: Improve seeders
  database/seeders/ApplicationPreviewSeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/EnvironmentSeeder.php
  database/seeders/EnvironmentVariableSeeder.php
  database/seeders/GitSeeder.php
  database/seeders/KubernetesSeeder.php
  database/seeders/LocalFileVolumeSeeder.php
  database/seeders/ProjectSettingSeeder.php
  database/seeders/ScheduledDatabaseBackupExecutionSeeder.php
  database/seeders/ScheduledDatabaseBackupSeeder.php
  database/seeders/ServiceApplicationSeeder.php
  database/seeders/ServiceDatabaseSeeder.php
  database/seeders/ServiceSeeder.php
  database/seeders/SubscriptionSeeder.php
  database/seeders/SwarmDockerSeeder.php
  database/seeders/WaitlistSeeder.php
  database/seeders/WebhookSeeder.php
  other/nightly/install.sh
Labels: 🏔️ Peaklabs

#3545 Feat: Improve Docker cleanup
  app/Actions/Server/CleanupDocker.php
  app/Jobs/DockerCleanupJob.php
  app/Livewire/Server/Form.php
  app/Models/Server.php
  database/migrations/2024_09_22_165240_add_advanced_options_to_cleanup_options_to_servers_settings_table.php
  resources/views/livewire/server/form.blade.php
Labels: 🏔️ Peaklabs

#3564 Fix: Removed some GH Actions and ordered issue templates
  .github/ISSUE_TEMPLATE/01_BUG_REPORT.yml
  .github/ISSUE_TEMPLATE/02_ENHANCEMENT_BOUNTY.yml
  .github/workflows/docker-image.yml
  .github/workflows/fix-php-code-style-issues
  .github/workflows/pr-build.yml
Labels: 🏔️ Peaklabs

#3576 Fix: Disable API by default and do not allow API key creation when API is disabled
  app/Livewire/Security/ApiTokens.php
  database/migrations/2024_09_26_083441_disable_api_by_default.php
  resources/views/livewire/security/api-tokens.blade.php
Labels: 🏔️ Peaklabs

#3585 Feat: GH Action that close stale issues and PRs
  .github/workflows/manage-stale-issues-and-prs.yml
Labels: 🏔️ Peaklabs

#3542 Fix: Volume issues in development
  CONTRIBUTING.md
  docker-compose.dev.yml
Labels: 🏔️ Peaklabs

#3608 Feat: Add debug bar for better debugging
  composer.json
  composer.lock
  storage/debugbar/.gitignore
Labels: 🏔️ Peaklabs

#3609 Fix: Remove memlock from dragonfly DB as it caused problems for some users
  app/Actions/Database/StartDragonfly.php
Labels: 🏔️ Peaklabs

#3202 feat: add Mailpit template
  public/svgs/mailpit.svg
  templates/compose/mailpit.yaml
Labels: ⚙️ New Service

#2351 feat: add Mixpost template
  public/svgs/mixpost.svg
  templates/compose/mixpost.yaml
Labels: ⚙️ New Service
