Repository coollabsio/coolify, pull requests merged in 2024-11, with the labels that each got.

#4066 Service Jenkins
  public/svgs/jenkins.svg
  templates/compose/jenkins.yaml
Labels: 💤 Waiting for feedback, ⚙️ Service

#2348 feat: add jitsi template
  public/svgs/jitsi.svg
  templates/compose/jitsi.yaml
Labels: 💤 Waiting for feedback, ⚙️ Service

#4162 Fix: Prod Dockerfile warning
  docker/prod/Dockerfile
Labels: 🏔️ Peaklabs

#3949 Fix: Projects can be deleted with resources
  app/Http/Controllers/Api/ProjectController.php
  app/Livewire/Project/DeleteEnvironment.php
  app/Livewire/Project/DeleteProject.php
  app/Models/Project.php
  resources/views/livewire/project/edit.blade.php
  resources/views/livewire/project/show.blade.php
Labels: 🏔️ Peaklabs

#3912 Fix: Error response from daemon: all predefined address pools have been fully subnetted
  other/nightly/install.sh
  scripts/install.sh
Labels: 🏔️ Peaklabs

#4106 add readeck service template
  public/svgs/readeck.svg
  templates/compose/readeck.yaml
Labels: ⚙️ Service

#4139 feat: add template for Wiki.js
  public/svgs/wikijs.svg
  templates/compose/wikijs.yaml
Labels: ⚙️ Service

#4120 add service: hoarder
  public/svgs/hoarder.svg
  templates/compose/hoarder.yaml
Labels: ⚙️ Service

#4111 Add new services Apprise-api, Cyberchef, Dashy, Faraday, Hoppscotch, Jupyter-notebook, Portainer, Web-Check | Fix Firefly, Postiz, Syncthing
  templates/compose/apprise-api.yaml
  templates/compose/cyberchef-x86.yaml
  templates/compose/dashy.yaml
  templates/compose/faraday.yaml
  templates/compose/firefly.yaml
  templates/compose/hoppscotch.yaml
  templates/compose/jupyter-notebook.yaml
  templates/compose/portainer.yaml
  templates/compose/postiz.yaml
  templates/compose/syncthing.yaml
  templates/compose/web-check.yaml
Labels: ⚙️ Service

#4193 v4.0.0-beta.364
  app/Livewire/Project/Application/Preview/Form.php
  app/Livewire/SettingsBackup.php
  app/Livewire/SettingsEmail.php
  app/Livewire/Source/Github/Create.php
  bootstrap/helpers/docker.php
  config/sentry.php
  config/version.php
  resources/views/livewire/project/application/general.blade.php
  resources/views/livewire/project/new/github-private-repository.blade.php
  resources/views/livewire/project/shared/scheduled-task/all.blade.php
  resources/views/livewire/server/show.blade.php
  resources/views/livewire/settings/index.blade.php
  resources/views/source/all.blade.php
  resources/views/source/github/new.blade.php
  resources/views/source/new.blade.php
  versions.json
Labels: 🏔️ Peaklabs

#4211 Keeping the Twenty Template Up to date
  templates/compose/twenty.yaml
Labels: ⚙️ Service

#4207 Fix mosquitto image
  public/svgs/mosquitto.png
  public/svgs/mosquitto.svg
Labels: ⚙️ Service

#4214 Trigger.dev template fix to disable SSL mode for db and include port in db host url
  templates/compose/trigger.yaml
Labels: ⚙️ Service

#4226 appwrite fix
  templates/compose/appwrite.yaml
Labels: ⚙️ Service

#4180 Feat: New Services
  public/svgs/apprise.png
  public/svgs/cyberchef.jpeg
  public/svgs/dashy.png
  public/svgs/faraday.png
  public/svgs/firefox.svg
  public/svgs/hoarder.svg
  public/svgs/hoppscotch.png
  public/svgs/jupyter.svg
  public/svgs/mosquitto.png
  public/svgs/mosquitto.svg
  public/svgs/portainer.png
  public/svgs/postiz.svg
  public/svgs/readeck.svg
  public/svgs/web-check.png
  public/svgs/wikijs.svg
  templates/compose/apprise-api.yaml
  templates/compose/appwrite.yaml
  templates/compose/cyberchef.yaml
  templates/compose/dashy.yaml
  templates/compose/faraday.yaml
  templates/compose/firefly.yaml
  templates/compose/firefox.yaml
  templates/compose/hoarder.yaml
  templates/compose/hoppscotch.yaml
  templates/compose/immich.yaml
  templates/compose/jupyter-notebook-python.yaml
  templates/compose/listmonk.yaml
  templates/compose/mattermost.yaml
  templates/compose/portainer.yaml
  templates/compose/postiz.yaml
  templates/compose/prefect.yaml
  templates/compose/readeck.yaml
  templates/compose/syncthing.yaml
  templates/compose/trigger.yaml
  templates/compose/twenty.yaml
  templates/compose/web-check.yaml
  templates/compose/wikijs.yaml
  templates/service-templates.json
Labels: 🏔️ Peaklabs

#4284 Fix: Root check in installer and add disk usage check
  scripts/install.sh
Labels: 🏔️ Peaklabs

#4274 Feat: Show private IP and port in installation script for easier Raspberry PI installation.
  scripts/install.sh
Labels: 🏔️ Peaklabs

#4285 Fix: Add warning to upgrade modal
  resources/views/livewire/upgrade.blade.php
Labels: 🏔️ Peaklabs

#4288 Fix for the Self-XSS
  app/Livewire/Project/Shared/Tags.php
Labels: 🟠 Medium Priority

#4287 Fix: Backups
  app/Livewire/Project/Database/CreateScheduledBackup.php
Labels: 🏔️ Peaklabs

#4286 Fix: Server IP/Domain validation
  app/Livewire/Server/New/ByIp.php
  app/Livewire/Server/Show.php
Labels: 🏔️ Peaklabs

#4293 Fix: Install openssl
  scripts/install.sh
Labels: 🏔️ Peaklabs

#4291 Fix: Ability to use the same ssh key in a different team
  app/Models/PrivateKey.php
Labels: 🏔️ Peaklabs

#4352 Fix: Test email 500 Error
  app/Livewire/Notifications/Email.php
  resources/views/livewire/notifications/email.blade.php
Labels: 🏔️ Peaklabs

#4359 Added convertx service.
  public/svgs/convertx.png
  templates/compose/convertx.yml
Labels: ⚙️ Service

#4262 feat(service): :sparkles: add mealie
  public/svgs/mealie.png
  templates/compose/mealie.yaml
Labels: ⚙️ Service

#4375 Add service: Maybe finance
  public/svgs/maybe.svg
  templates/compose/maybe.yaml
Labels: ⚙️ Service

#4209 Feat: Private Bin and Redlib Service
  public/svgs/gothub.svg
  public/svgs/privatebin.svg
  public/svgs/redlib.svg
  templates/compose/gothub.yaml
  templates/compose/privatebin.yaml
  templates/compose/redlib.yaml
Labels: ⚙️ Service

#4366 Feat: Improve Core Maintainers readme
  README.md
Labels: 🏔️ Peaklabs
