Repository coollabsio/coolify, pull requests merged in 2024-12, with the labels that each got.

#4439 fix formbricks template
  templates/compose/formbricks.yaml
Labels: ⚙️ Service

#4452 Add KVM Support for macos and windows template
  templates/compose/macos.yaml
  templates/compose/windows.yaml
Labels: ⚙️ Service

#4429 Adding Overseerr
  public/svgs/overseerr.svg
  templates/compose/overseerr.yaml
Labels: 💤 Waiting for feedback, ⚙️ Service

#4415 Adding Plex
  public/svgs/plex.svg
  templates/compose/plex.yaml
Labels: 💤 Waiting for feedback, ⚙️ Service

#4470 Feat: Ability to rename GitHub App
  app/Http/Controllers/Webhook/Github.php
  app/Livewire/Source/Github/Change.php
  database/seeders/GithubAppSeeder.php
  resources/views/livewire/source/github/change.blade.php
Labels: 🏔️ Peaklabs

#4381 Add no encryption option for SMTP settings
  app/Livewire/Notifications/Email.php
  app/Livewire/SettingsEmail.php
  app/Notifications/Channels/EmailChannel.php
  resources/views/livewire/notifications/email.blade.php
  resources/views/livewire/settings-email.blade.php
Labels: 💤 Waiting for feedback

#3845 feat: allow disabling default redirect, set status to 503
  app/Actions/Proxy/StartProxy.php
  app/Listeners/ProxyStartedNotification.php
  app/Livewire/Server/Proxy.php
  app/Livewire/Server/Proxy/Deploy.php
  app/Models/Server.php
  bootstrap/helpers/proxy.php
  resources/views/livewire/server/proxy.blade.php
  resources/views/livewire/server/proxy/dynamic-configurations.blade.php
Labels: 🛠️ Feature

#4264 feat: add slack notifications
  app/Jobs/SendMessageToSlackJob.php
  app/Livewire/Notifications/Slack.php
  app/Models/Team.php
  app/Notifications/Application/DeploymentFailed.php
  app/Notifications/Application/DeploymentSuccess.php
  app/Notifications/Application/StatusChanged.php
  app/Notifications/Channels/SendsSlack.php
  app/Notifications/Channels/SlackChannel.php
  app/Notifications/Container/ContainerRestarted.php
  app/Notifications/Container/ContainerStopped.php
  app/Notifications/Database/BackupFailed.php
  app/Notifications/Database/BackupSuccess.php
  app/Notifications/Dto/SlackMessage.php
  app/Notifications/Internal/GeneralNotification.php
  app/Notifications/ScheduledTask/TaskFailed.php
  app/Notifications/Server/DockerCleanup.php
  app/Notifications/Server/ForceDisabled.php
  app/Notifications/Server/ForceEnabled.php
  app/Notifications/Server/HighDiskUsage.php
  app/Notifications/Server/Reachable.php
  app/Notifications/Server/Unreachable.php
  app/Notifications/Test.php
  bootstrap/helpers/shared.php
  database/migrations/2024_11_12_213200_add_slack_notifications_to_teams_table.php
  resources/views/components/notification/navbar.blade.php
  resources/views/livewire/notifications/slack.blade.php
  routes/web.php
Labels: 🛠️ Feature

#4526 added the fileflows service
  public/svgs/fileflows.svg
  templates/compose/fileflows.yaml
Labels: ⚙️ Service

#4536 Fix: Migration error
  database/migrations/2024_06_11_081614_add_www_non_www_redirect.php
Labels: 🏔️ Peaklabs

#4530 Adds template for Sonatype Nexus service
  public/svgs/nexus-arm.png
  public/svgs/nexus.png
  templates/compose/nexus-arm.yaml
  templates/compose/nexus.yaml
Labels: ⚙️ Service

#3840 feature: :passport_control: Integrate Authentik Authentication with Coolify
  app/Livewire/SettingsOauth.php
  app/Providers/EventServiceProvider.php
  bootstrap/helpers/socialite.php
  composer.json
  composer.lock
  config/services.php
  database/migrations/2024_09_29_163625_add_base_url_to_oauth_settings_table.php
  database/seeders/OauthSettingSeeder.php
  lang/en.json
  resources/views/livewire/settings-oauth.blade.php
Labels: 🛠️ Feature

#4543 feat(notification): add Pushover
  app/Console/Commands/NotifyDemo.php
  app/Jobs/SendMessageToPushoverJob.php
  app/Livewire/Notifications/Pushover.php
  app/Models/PushoverNotificationSettings.php
  app/Models/Team.php
  app/Notifications/Application/DeploymentFailed.php
  app/Notifications/Application/DeploymentSuccess.php
  app/Notifications/Application/StatusChanged.php
  app/Notifications/Channels/PushoverChannel.php
  app/Notifications/Channels/SendsPushover.php
  app/Notifications/Container/ContainerRestarted.php
  app/Notifications/Container/ContainerStopped.php
  app/Notifications/Database/BackupFailed.php
  app/Notifications/Database/BackupSuccess.php
  app/Notifications/Dto/PushoverMessage.php
  app/Notifications/Internal/GeneralNotification.php
  app/Notifications/ScheduledTask/TaskFailed.php
  app/Notifications/ScheduledTask/TaskSuccess.php
  app/Notifications/Server/DockerCleanupFailed.php
  app/Notifications/Server/DockerCleanupSuccess.php
  app/Notifications/Server/ForceDisabled.php
  app/Notifications/Server/ForceEnabled.php
  app/Notifications/Server/HighDiskUsage.php
  app/Notifications/Server/Reachable.php
  app/Notifications/Server/Unreachable.php
  app/Notifications/Test.php
  app/Traits/HasNotificationSettings.php
  database/migrations/2024_12_11_135026_create_pushover_notification_settings_table.php
  resources/views/components/notification/navbar.blade.php
  resources/views/livewire/notifications/pushover.blade.php
  routes/web.php
Labels: 🛠️ Feature

#4546 Add new service dolibarr
  public/svgs/dolibarr.png
  templates/compose/dolibarr.yaml
Labels: 💤 Waiting for feedback, ⚙️ Service

#4610 Fix: Docker Cleanup schedule
  app/Console/Kernel.php
  app/Livewire/Server/Advanced.php
  database/migrations/2024_12_17_140637_add_server_disk_usage_check_frequency_to_server_settings_table.php
  resources/views/livewire/server/advanced.blade.php
Labels: 🏔️ Peaklabs

#4586 Fix: Unreachable Notifications
  app/Console/Commands/CloudCleanupSubscriptions.php
  app/Events/ServerReachabilityChanged.php
  app/Jobs/ServerCheckJob.php
  app/Livewire/Server/Show.php
  app/Models/Server.php
  app/Models/ServerSetting.php
  app/Models/Team.php
  app/Notifications/Application/DeploymentSuccess.php
Labels: 🏔️ Peaklabs

#3950 Fix: Multiple Init script fixes and some other Postgres fixes
  app/Actions/Database/StartPostgresql.php
  app/Livewire/Project/Database/Postgresql/General.php
  resources/views/livewire/project/database/init-script.blade.php
Labels: 🏔️ Peaklabs

#4324 feat: add some new labels to every container
  app/Actions/Database/StartClickhouse.php
  app/Actions/Database/StartDragonfly.php
  app/Actions/Database/StartKeydb.php
  app/Actions/Database/StartMariadb.php
  app/Actions/Database/StartMongodb.php
  app/Actions/Database/StartMysql.php
  app/Actions/Database/StartPostgresql.php
  app/Actions/Database/StartRedis.php
  app/Jobs/ApplicationDeploymentJob.php
  bootstrap/helpers/docker.php
  bootstrap/helpers/shared.php
Labels: 🛠️ Feature

#4576 Add Cockpit CMS service / template
  public/svgs/cockpit.svg
  templates/compose/cockpit.yaml
Labels: ⚙️ Service

#4649 v4.0.0-beta.380
  app/Console/Commands/CloudCleanupSubscriptions.php
  app/Events/ServerReachabilityChanged.php
  app/Jobs/ServerCheckJob.php
  app/Livewire/Notifications/Email.php
  app/Livewire/Server/Show.php
  app/Livewire/SettingsEmail.php
  app/Models/Server.php
  app/Models/ServerSetting.php
  app/Models/Team.php
  app/Notifications/Channels/EmailChannel.php
  bootstrap/helpers/notifications.php
  config/constants.php
  database/migrations/2024_12_10_122142_encrypt_instance_settings_email_columns.php
  database/migrations/2024_12_23_142402_update_email_encryption_values.php
  database/seeders/OauthSettingSeeder.php
  docker-compose.dev.yml
  docker-compose.prod.yml
  docker-compose.windows.yml
  docker/coolify-realtime/terminal-server.js
  docker/development/etc/nginx/site-opts.d/http.conf
  docker/production/etc/nginx/site-opts.d/http.conf
  other/nightly/docker-compose.prod.yml
  other/nightly/docker-compose.windows.yml
  resources/views/livewire/notifications/email.blade.php
  resources/views/livewire/settings-email.blade.php
  versions.json
Labels: 🏔️ Peaklabs
