Repository coollabsio/coolify, pull requests merged in 2025-03, with the labels that each got.

#5163 Update Foundry VTT template
  templates/compose/foundryvtt.yaml
Labels: ⚙️ Service

#5125 Add DenoKV one click service
  public/svgs/denoKV.svg
  templates/compose/denoKV.yaml
Labels: ⚙️ Service

#5027 feat: Full SSL Support for all Databases
  app/Actions/Database/StartDragonfly.php
  app/Actions/Database/StartKeydb.php
  app/Actions/Database/StartMariadb.php
  app/Actions/Database/StartMongodb.php
  app/Actions/Database/StartMysql.php
  app/Actions/Database/StartPostgresql.php
  app/Actions/Database/StartRedis.php
  app/Actions/Server/InstallDocker.php
  app/Console/Kernel.php
  app/Helpers/SslHelper.php
  app/Jobs/DeleteResourceJob.php
  app/Jobs/RegenerateSslCertJob.php
  app/Livewire/Project/Database/Dragonfly/General.php
  app/Livewire/Project/Database/Keydb/General.php
  app/Livewire/Project/Database/Mariadb/General.php
  app/Livewire/Project/Database/Mongodb/General.php
  app/Livewire/Project/Database/Mysql/General.php
  app/Livewire/Project/Database/Postgresql/General.php
  app/Livewire/Project/Database/Redis/General.php
  app/Livewire/Server/Advanced.php
  app/Models/LocalFileVolume.php
  app/Models/LocalPersistentVolume.php
  app/Models/SslCertificate.php
  app/Models/StandaloneClickhouse.php
  app/Models/StandaloneDragonfly.php
  app/Models/StandaloneKeydb.php
  app/Models/StandaloneMariadb.php
  app/Models/StandaloneMongodb.php
  app/Models/StandaloneMysql.php
  app/Models/StandalonePostgresql.php
  app/Models/StandaloneRedis.php
  app/Notifications/SslExpirationNotification.php
  app/Traits/HasNotificationSettings.php
  app/View/Components/Forms/Select.php
  bootstrap/helpers/databases.php
  database/migrations/2025_01_27_102616_add_ssl_fields_to_database_tables.php
  database/migrations/2025_01_27_153741_create_ssl_certificates_table.php
  database/migrations/2025_01_30_125223_encrypt_local_file_volumes_fields.php
  database/seeders/CaSslCertSeeder.php
  database/seeders/DatabaseSeeder.php
  database/seeders/ProductionSeeder.php
  resources/js/app.js
  resources/js/components/MagicBar.vue
  resources/views/components/forms/copy-button.blade.php
  resources/views/components/modal-confirmation.blade.php
  resources/views/components/server/sidebar.blade.php
  resources/views/emails/ssl-certificate-renewed.blade.php
  resources/views/livewire/profile/index.blade.php
  resources/views/livewire/project/database/dragonfly/general.blade.php
  resources/views/livewire/project/database/keydb/general.blade.php
  resources/views/livewire/project/database/mariadb/general.blade.php
  resources/views/livewire/project/database/mongodb/general.blade.php
  resources/views/livewire/project/database/mysql/general.blade.php
  resources/views/livewire/project/database/postgresql/general.blade.php
  resources/views/livewire/project/database/redis/general.blade.php
  resources/views/livewire/server/advanced.blade.php
  scripts/install.sh
Labels: 🛠️ Feature, 🏔️ Peaklabs

#5344 feat(api): improve services API
  app/Http/Controllers/Api/ServicesController.php
  openapi.yaml
  routes/api.php
Labels: 💤 Waiting for changes
