Repository coollabsio/coolify, pull requests merged in 2025-09, with the labels that each got.

#6510 fix: appwrite template - 500 errors, missing env vars etc.
  templates/compose/appwrite.yaml
Labels: ⚙️ Service, 🔄 Linear

#6629 feat(docker): add build secrets
  app/Jobs/ApplicationDeploymentJob.php
  app/Livewire/Project/Shared/EnvironmentVariable/All.php
  database/migrations/2025_09_17_081112_add_use_build_secrets_to_application_settings.php
  resources/views/livewire/project/shared/environment-variable/all.blade.php
Labels: 🛠️ Feature

#6644 fix: hide sensitive email change fields in team member responses (#GHSA-927g-56xp-6427)
  app/Http/Controllers/Api/TeamController.php
Labels: 🔄 Linear

#6496 fix(domains) url validation silently fails with surrounding whitespace
  app/Livewire/Project/Application/General.php
  app/Livewire/Project/Service/EditDomain.php
  app/Livewire/Project/Service/ServiceApplicationView.php
Labels: ✨ Enhancement, 🔄 Linear

#5697 [Enhancement]: See and manage DB backups via API
  app/Http/Controllers/Api/DatabasesController.php
  routes/api.php
Labels: 🙋 Bounty claim, 🔄 Linear

#6541 feat(core): update coolify logo files
  public/coolify-logo-dev-transparent.png
  public/coolify-logo-dev-transparent.svg
  public/coolify-logo-monochrome.png
  public/coolify-logo-monochrome.svg
  public/coolify-logo-red.png
  public/coolify-logo-red.svg
  public/coolify-logo.svg
  public/coolify-transparent.png
Labels: ✨ Enhancement

#6497 refactor: improve ENV handling during installation and upgrades
  other/nightly/install.sh
  other/nightly/upgrade.sh
  scripts/install-1.6.sh
  scripts/install-1.7.sh
  scripts/install.sh
  scripts/upgrade.sh
Labels: 🏔️ Peaklabs, 🔄 Linear

#6574 feat: Add SSH command process timeout configuration
  app/Traits/ExecuteRemoteCommand.php
Labels: ✨ Enhancement

#6572 fix(socialite): add custom base URL support for GitLab provider in OAuth settings
  bootstrap/helpers/socialite.php
  resources/views/livewire/settings-oauth.blade.php
Labels: ✨ Enhancement

#6725 fix(ui): long text on helper popup not wrapping based on screensize
  resources/css/utilities.css
Labels: UI/UX

#6724 chore(ui): improve application healthcheck page
  app/Livewire/Project/Shared/HealthChecks.php
  resources/views/livewire/project/shared/health-checks.blade.php
Labels: ✨ Enhancement, php, UI/UX

#6714 feat(ui): Change theme color
  resources/views/livewire/settings-dropdown.blade.php
Labels: ✨ Enhancement, UI/UX
