Repository coollabsio/coolify, pull requests merged in 2025-01, with the labels that each got.

#4654 update supabase template
  templates/compose/supabase.yaml
Labels: ⚙️ Service

#4700 Fix Redis Not defined issue in Trigger.dev Ext db template.
  templates/compose/trigger-with-external-database.yaml
Labels: ⚙️ Service

#4711 Fixing the CSRF bug for labelstudio versions 1.14.0 and higher
  templates/compose/labelstudio.yaml
Labels: ⚙️ Service

#4767 fix: edge case where backup executions could be null
  app/Livewire/Project/Database/BackupExecutions.php
Labels: 🏔️ Peaklabs

#4814 fix: instance wide GitHub apps
  app/Models/Team.php
Labels: 🏔️ Peaklabs

#4777 fix/feat: Improves Cloning
  app/Http/Controllers/Api/ApplicationsController.php
  app/Jobs/ApplicationDeploymentJob.php
  app/Jobs/VolumeCloneJob.php
  app/Livewire/Project/Application/General.php
  app/Livewire/Project/CloneMe.php
  app/Livewire/Project/Shared/ResourceOperations.php
  app/Livewire/Project/Shared/Storages/Add.php
  database/migrations/2025_01_08_154008_switch_up_readonly_labels.php
  resources/views/components/forms/monaco-editor.blade.php
  resources/views/livewire/project/application/general.blade.php
  resources/views/livewire/project/clone-me.blade.php
  resources/views/livewire/project/shared/resource-operations.blade.php
Labels: 🏔️ Peaklabs

#4818 Feat: Improve backup retention (for database backups)
  app/Jobs/DatabaseBackupJob.php
  app/Livewire/Project/Database/BackupEdit.php
  app/Livewire/Project/Database/BackupExecutions.php
  bootstrap/helpers/databases.php
  database/migrations/2025_01_13_130238_add_backup_retention_fields_to_scheduled_database_backups_table.php
  resources/views/livewire/project/database/backup-edit.blade.php
  resources/views/livewire/project/database/backup-executions.blade.php
Labels: 🏔️ Peaklabs

#4624 Add nodebb service
  public/svgs/nodebb.svg
  templates/compose/nodebb.yaml
Labels: ⚙️ Service

#4639 Add calibre-web service
  public/svgs/calibre-web.svg
  templates/compose/calibre-web.yaml
Labels: ⚙️ Service

#4759 feat: template for Gotenberg, a Docker-powered stateless API for PDF files
  public/svgs/gotenberg.png
  templates/compose/gotenberg.yaml
Labels: ⚙️ Service, 💤 Waiting for changes

#4796 Feat: Improve navigation performance
  resources/views/components/navbar.blade.php
  resources/views/components/notification/navbar.blade.php
  resources/views/components/resources/breadcrumbs.blade.php
  resources/views/components/security/navbar.blade.php
  resources/views/components/server/navbar.blade.php
  resources/views/components/server/sidebar-proxy.blade.php
  resources/views/components/server/sidebar.blade.php
  resources/views/components/settings/navbar.blade.php
  resources/views/components/team/navbar.blade.php
  resources/views/livewire/dashboard.blade.php
  resources/views/livewire/destination/index.blade.php
  resources/views/livewire/project/application/configuration.blade.php
  resources/views/livewire/project/application/deployment/index.blade.php
  resources/views/livewire/project/application/heading.blade.php
  resources/views/livewire/project/database/configuration.blade.php
  resources/views/livewire/project/database/heading.blade.php
  resources/views/livewire/project/database/scheduled-backups.blade.php
  resources/views/livewire/project/environment-edit.blade.php
  resources/views/livewire/project/index.blade.php
  resources/views/livewire/project/resource/index.blade.php
  resources/views/livewire/project/service/configuration.blade.php
  resources/views/livewire/project/service/index.blade.php
  resources/views/livewire/project/service/navbar.blade.php
  resources/views/livewire/project/shared/scheduled-task/all.blade.php
  resources/views/livewire/project/show.blade.php
  resources/views/livewire/security/private-key/index.blade.php
  resources/views/livewire/server/index.blade.php
  resources/views/livewire/server/proxy/deploy.blade.php
  resources/views/livewire/shared-variables/environment/index.blade.php
  resources/views/livewire/shared-variables/index.blade.php
  resources/views/livewire/shared-variables/project/index.blade.php
  resources/views/livewire/source/github/change.blade.php
  resources/views/livewire/storage/index.blade.php
  resources/views/livewire/tags/deployments.blade.php
  resources/views/livewire/tags/show.blade.php
  resources/views/source/all.blade.php
Labels: 🏔️ Peaklabs

#4841 Added template for joomla with MariaDB
  public/svgs/joomla.svg
  templates/compose/joomla-with-mariadb.yaml
Labels: ⚙️ Service

#4832 Add logo for lowcoder
  public/svgs/lowcoder.svg
  public/svgs/openblocks.svg
Labels: ⚙️ Service

#4754 Improves: GitHub handling, AppServiceProvider and 500 error message rendering
  app/Jobs/GithubAppPermissionJob.php
  app/Livewire/Project/New/GithubPrivateRepository.php
  app/Livewire/Source/Github/Change.php
  app/Models/Application.php
  app/Providers/AppServiceProvider.php
  bootstrap/helpers/github.php
  composer.json
  composer.lock
  config/purify.php
  resources/views/errors/500.blade.php
  resources/views/livewire/project/application/source.blade.php
  resources/views/livewire/project/new/github-private-repository.blade.php
  resources/views/livewire/source/github/change.blade.php
Labels: 🏔️ Peaklabs

#4847 feat: Ability to create root user via environment variables
  .env.production
  database/seeders/ProductionSeeder.php
  database/seeders/RootUserSeeder.php
Labels: 🏔️ Peaklabs

#4724 fix: broken trigger.dev templates
  templates/compose/trigger-with-external-database.yaml
  templates/compose/trigger.yaml
Labels: ⚙️ Service
