Repository coollabsio/coolify, pull requests merged in 2025-08, with the labels that each got.

#6306 feat(lang): add Polish language & improve forgot_password translation
  lang/ar.json
  lang/az.json
  lang/cs.json
  lang/de.json
  lang/en.json
  lang/es.json
  lang/fa.json
  lang/fr.json
  lang/id.json
  lang/it.json
  lang/ja.json
  lang/no.json
  lang/pl.json
  lang/pt-br.json
  lang/pt.json
  lang/ro.json
  lang/tr.json
  lang/vi.json
  lang/zh-cn.json
  lang/zh-tw.json
  resources/views/auth/forgot-password.blade.php
  resources/views/auth/login.blade.php
Labels: ✨ Enhancement

#6264 feat(service): update Authentik template
  templates/compose/authentik.yaml
Labels: ⚙️ Service

#6201 feat(services): add Chroma service
  public/svgs/chroma.svg
  templates/compose/chroma.yaml
Labels: ⚙️ Service, 💤 Waiting for changes

#6301 chore(service): update Langfuse template to v3
  public/svgs/langfuse.png
  public/svgs/langfuse.svg
  templates/compose/langfuse.yaml
Labels: ⚙️ Service

#5310 feat(service): add OpenPanel template
  public/svgs/openpanel.svg
  templates/compose/openpanel.yaml
Labels: ⚙️ Service

#5654 feat(service): add librechat template
  public/svgs/librechat.svg
  templates/compose/librechat.yaml
Labels: ⚙️ Service
