Repository coollabsio/coolify, pull requests merged in 2025-05, with the labels that each got.

#5784 v4.0.0-beta.417
  README.md
  app/Console/Commands/CleanupRedis.php
  app/Console/Kernel.php
  app/Jobs/CleanupInstanceStuffsJob.php
  app/Jobs/DockerCleanupJob.php
  app/Jobs/PushServerUpdateJob.php
  app/Jobs/RestartProxyJob.php
  app/Jobs/ServerCheckJob.php
  config/constants.php
  other/nightly/versions.json
  versions.json
Labels: 🐰 Release The Rabbit

#4797 Add soketi-app-manager service template 🚀
  public/svgs/soketi-app-manager.svg
  templates/compose/soketi-app-manager.yaml
Labels: ⚙️ Service

#5178 BugSink Integration - fix - working with cloudflared
  templates/compose/bugsink.yaml
Labels: ⚙️ Service

#5032 feat: Add memos service tamplate
  public/svgs/memos.png
  templates/compose/memos.yaml
Labels: ⚙️ Service, 💤 Waiting for changes

#5232 Add Ryot service
  public/svgs/ryot.svg
  templates/compose/ryot.yaml
Labels: ⚙️ Service

#5809 feat: add Paymenter template
  public/svgs/paymenter.svg
  templates/compose/paymenter.yaml
Labels: 💤 Waiting for feedback

#4867 feat: New Service CodiMD
  public/svgs/codimd.png
  templates/compose/codimd.yaml
Labels: ⚙️ Service

#5827 Update convex.yaml
  templates/compose/convex.yaml
Labels: 💤 Waiting for feedback

#5643 feat: Add Typesense service template
  public/svgs/typesense.webp
  templates/compose/typesense.yaml
Labels: 💤 Waiting for feedback

#5079 feat(service): add PG Back Web service
  public/svgs/pgbackweb.png
  templates/compose/pgbackweb.yaml
Labels: ⚙️ Service, 💤 Waiting for changes

#5795 feat(service): update Maybe service
  templates/compose/maybe.yaml
Labels: 💤 Waiting for changes

#4891 feat(service): add apache superset service
  public/svgs/superset.svg
  templates/compose/superset-unofficial-with-postgresql.yaml
Labels: ⚙️ Service, 💤 Waiting for changes

#5817 feat(service): add Seafile service
  public/svgs/seafile.svg
  templates/compose/seafile.yaml
Labels: 💤 Waiting for changes

#5873 feat(service): add Netbird-Client service
  public/svgs/netbird.png
  templates/compose/netbird-client.yaml
Labels: ⚙️ Service, 💤 Waiting for changes

#5881 feat(api): Add latest query param to Service restart API
  app/Actions/Service/RestartService.php
  app/Http/Controllers/Api/ServicesController.php
  public/svgs/typesense.webp
Labels: 🐰 Release The Rabbit
